#!/usr/bin/env python3
"""
Interactive configuration wizard for generating a .env file based on .env.example.
"""

import os
import sys


def main():
    """
    Prompt the user for configuration values and generate a .env file.
    """
    cwd = os.getcwd()
    example_path = os.path.join(cwd, ".env.example")
    if not os.path.exists(example_path):
        sys.exit("Error: .env.example file not found in current directory.")

    entries = []
    with open(example_path, encoding="utf-8") as f:
        for line in f:
            stripped = line.strip()
            if not stripped or stripped.startswith("#"):
                continue
            if "=" not in stripped:
                continue
            key, default = stripped.split("=", 1)
            entries.append((key, default))

    print("Interactive setup - populate your .env file")
    values = {}
    for key, default in entries:
        prompt = f"{key} [{default}]: "
        if any(sensitive in key for sensitive in ("PASSWORD", "TOKEN", "KEY")):
            try:
                import getpass

                val = getpass.getpass(prompt)
            except ImportError:
                val = input(prompt)
            if not val:
                val = default
        else:
            val = input(prompt).strip()
            if not val:
                val = default
        values[key] = val

    env_path = os.path.join(cwd, ".env")
    with open(env_path, "w", encoding="utf-8") as f:
        f.write("# Generated by mail2do-configure\n")
        for key, _ in entries:
            f.write(f"{key}={values[key]}\n")

    print(f"Written {env_path}. Remember not to commit your .env to version control.")


if __name__ == "__main__":
    main()